#!/bin/bash
# Replace homebrew source with tsinghua mirror
# From: https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

echo "Replace homebrew with tsinghua mirror or the original source?: "
echo "y -> tsinghua"
echo "n -> original"
read yn
case $yn in
    y )
        git -C "$(brew --repo)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
        git -C "$(brew --repo homebrew/core)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
        git -C "$(brew --repo homebrew/cask)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git
        brew update
        ;;
    n )
        git -C "$(brew --repo)" remote set-url origin https://github.com/Homebrew/brew.git
        git -C "$(brew --repo homebrew/core)" remote set-url origin https://github.com/Homebrew/homebrew-core.git
        git -C "$(brew --repo homebrew/cask)" remote set-url origin https://github.com/Homebrew/homebrew-cask.git
        brew update
        ;;
    * )
        echo "Input y or n"
        ;;
esac

echo "Homebrew-bottles"
echo 'export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles' >> ~/.bash_profile
source ~/.bash_profile
