#!/bin/env sh

# Setup homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew tap homebrew/cask-fonts

# Setup Essential
brew install wget curl sqlite3 openssl xz zlib git

# Setup git
git config --global user.name secf4ult
git config --global user.email "secf4ult@outlook.com"

# Clone dotfiles
git clone https://github.com/secf4ult/dotfiles $HOME/.dotfiles
DOTFILES="$HOME/.dotfiles"

# Setup development environment
# Setup nodenv, pyenv, rbenv
brew install nodenv
brew install pyenv
brew install rbenv
# Setup rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Setup zsh
brew install zsh
# Setup oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ln -fs $DOTFILES/zsh/.zshrc $HOME/.zshrc
ln -fs $DOTFILES/.zshenv $HOME/.zshenv
ln -fs $DOTFILES/.p10k.zsh $HOME/.p10k.zsh

# Setup tmux
brew install tmux
ln -fs $DOTFILES/.tmux_conf $HOME/.tmux.conf

# Setup vim
ln -fs $DOTFILES/.vimrc $HOME/.vimrc
# Setup vundle
git clone --depth 1 https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim

# Setup docker
# brew install docker

# Setup fonts
brew tap homebrew/cask-fonts
# brew cask install font-meslo-nerd-font-mono font-firacode-nerd-font

# Setup apps
brew install ripgrep

# Setup gui apps
bred tap homebrew/cask-versions
brew cask install visual-studio-code \
                  microsoft-edge-dev google-chrome-dev wireshark postman \
                  mpv

# Setup vscode
mkdir -p $HOME/Library/Application\ Support/Code/User
ln -fs DOTFILES/vscode/settings $HOME/Library/Application\ Support/Code/User/settings.json

# Setup mpv
mkdir -p $HOME/.config/mpv
ln -fs DOTFILES/mpv/mpv.conf $HOME/.config/mpv/mpv.conf
ln -fs DOTFILES/mpv/input.conf $HOME/.config/mpv/input.conf

# Setup transmission
brew cask install transmission
